// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHUmC7cEbzxurqUXGbuInbeCnQAUBLiX0',
    appId: '1:51259478934:web:1f5586d49f94a3eb00c3b7',
    messagingSenderId: '51259478934',
    projectId: 'wisata-babel',
    authDomain: 'wisata-babel.firebaseapp.com',
    storageBucket: 'wisata-babel.firebasestorage.app',
    measurementId: 'G-FWSTYX9Q0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnmsN4qIlyRc6ylJlIZgdUrpvbMnSv2mk',
    appId: '1:51259478934:android:e71a74efc4c50f3200c3b7',
    messagingSenderId: '51259478934',
    projectId: 'wisata-babel',
    storageBucket: 'wisata-babel.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPph0TNvz-2ULikP89Sl8Kbbc7YBp9T0',
    appId: '1:51259478934:ios:29c9eb70291e69f100c3b7',
    messagingSenderId: '51259478934',
    projectId: 'wisata-babel',
    storageBucket: 'wisata-babel.firebasestorage.app',
    iosBundleId: 'com.example.projectUtsPariwisata',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPph0TNvz-2ULikP89Sl8Kbbc7YBp9T0',
    appId: '1:51259478934:ios:29c9eb70291e69f100c3b7',
    messagingSenderId: '51259478934',
    projectId: 'wisata-babel',
    storageBucket: 'wisata-babel.firebasestorage.app',
    iosBundleId: 'com.example.projectUtsPariwisata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHUmC7cEbzxurqUXGbuInbeCnQAUBLiX0',
    appId: '1:51259478934:web:683b2f618b61f42500c3b7',
    messagingSenderId: '51259478934',
    projectId: 'wisata-babel',
    authDomain: 'wisata-babel.firebaseapp.com',
    storageBucket: 'wisata-babel.firebasestorage.app',
    measurementId: 'G-76TL945VBB',
  );

}